#!/usr/bin/env node

/**
 * Bakal · Notion Database Setup Script
 *
 * Creates the 4 required databases in your Notion workspace:
 *   1. Campagnes · Résultats
 *   2. Campagnes · Diagnostics
 *   3. Campagnes · Historique Versions
 *   4. Mémoire Cross-Campagne
 *
 * Prerequisites:
 *   1. Create a Notion integration at https://www.notion.so/my-integrations
 *   2. Set NOTION_TOKEN in your .env file
 *   3. Share a parent page with your integration (... → Connections → Add)
 *   4. Optionally set NOTION_PARENT_PAGE_ID (auto-discovered if missing)
 *
 * Usage:
 *   npm run setup-notion
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Client } = require('@notionhq/client');

const ENV_PATH = path.join(__dirname, '..', '.env');

const notion = new Client({ auth: process.env.NOTION_TOKEN });

async function findParentPage() {
  // If NOTION_PARENT_PAGE_ID is set, use it
  if (process.env.NOTION_PARENT_PAGE_ID) {
    console.log(`📌 Using configured parent page: ${process.env.NOTION_PARENT_PAGE_ID}`);
    return process.env.NOTION_PARENT_PAGE_ID;
  }

  // Auto-discover: search workspace for any page the integration has access to
  console.log('🔍 No NOTION_PARENT_PAGE_ID set, searching workspace...');
  const search = await notion.search({
    filter: { property: 'object', value: 'page' },
    page_size: 20,
  });

  if (search.results.length === 0) {
    console.error('❌ No pages found in workspace.');
    console.error('   Make sure you shared a page with your integration:');
    console.error('   Go to any Notion page → ... → Connections → Add your integration');
    process.exit(1);
  }

  // Prefer a page named "Bakal", "Stanko", "Projet", or "Welcome"
  const keywords = ['bakal', 'stanko', 'projet', 'project', 'welcome', 'hub'];
  for (const page of search.results) {
    const props = page.properties || {};
    const titleProp = props.title || props.Name || Object.values(props).find(p => p.type === 'title');
    const title = (titleProp?.title?.[0]?.plain_text || '').toLowerCase();
    if (keywords.some(kw => title.includes(kw))) {
      console.log(`📌 Found matching page: "${titleProp.title[0].plain_text}" (${page.id})`);
      return page.id;
    }
  }

  // Fallback: use the first page
  const first = search.results[0];
  const props = first.properties || {};
  const titleProp = props.title || props.Name || Object.values(props).find(p => p.type === 'title');
  const title = titleProp?.title?.[0]?.plain_text || '(untitled)';
  console.log(`📌 Using first available page: "${title}" (${first.id})`);
  return first.id;
}

function appendToEnv(entries) {
  let content = fs.readFileSync(ENV_PATH, 'utf8');

  // Add Notion database section if not present
  if (!content.includes('NOTION_DB_RESULTATS')) {
    content += '\n# --- Notion Database IDs (auto-generated by setup-notion) ---\n';
  }

  for (const [key, value] of Object.entries(entries)) {
    // Replace existing line or append
    const regex = new RegExp(`^${key}=.*$`, 'm');
    if (regex.test(content)) {
      content = content.replace(regex, `${key}=${value}`);
    } else {
      content += `${key}=${value}\n`;
    }
  }

  fs.writeFileSync(ENV_PATH, content);
}

async function main() {
  console.log('🔧 Bakal, Notion Database Setup\n');

  if (!process.env.NOTION_TOKEN) {
    console.error('❌ NOTION_TOKEN is not set. Add it to your .env file.');
    process.exit(1);
  }

  // Verify connection
  try {
    const me = await notion.users.me();
    console.log(`✅ Connected to Notion (${me.name || me.type})\n`);
  } catch (err) {
    console.error('❌ Cannot connect to Notion:', err.message);
    console.error('   Check your NOTION_TOKEN in .env');
    process.exit(1);
  }

  // Check if databases already exist in workspace
  console.log('🔍 Checking for existing databases...');
  const existing = await notion.search({
    filter: { property: 'object', value: 'database' },
    page_size: 50,
  });

  const dbNames = {
    resultats: 'Campagnes, Résultats',
    diagnostics: 'Campagnes, Diagnostics',
    historique: 'Campagnes, Historique Versions',
    memoire: 'Mémoire Cross-Campagne',
  };

  const found = {};
  for (const db of existing.results) {
    const title = db.title?.[0]?.plain_text || '';
    for (const [key, name] of Object.entries(dbNames)) {
      if (title === name) {
        found[key] = db.id;
        console.log(`   ✓ Found existing "${name}" (${db.id})`);
      }
    }
  }

  if (Object.keys(found).length === 4) {
    console.log('\n✅ All 4 databases already exist!');
    console.log('   Saving IDs to .env...\n');
    appendToEnv({
      NOTION_DB_RESULTATS: found.resultats,
      NOTION_DB_DIAGNOSTICS: found.diagnostics,
      NOTION_DB_HISTORIQUE: found.historique,
      NOTION_DB_MEMOIRE: found.memoire,
    });
    console.log('✅ .env updated. Restart the server to apply.');
    return;
  }

  // Find parent page
  const parentPageId = await findParentPage();

  const created = { ...found };

  // ──────────────────────────────────────────
  // 1. Campagnes · Résultats
  // ──────────────────────────────────────────
  if (!created.resultats) {
    console.log('\n📊 Creating "Campagnes, Résultats"...');
    const resultats = await notion.databases.create({
      parent: { type: 'page_id', page_id: parentPageId },
      title: [{ type: 'text', text: { content: 'Campagnes, Résultats' } }],
      icon: { type: 'emoji', emoji: '📊' },
      properties: {
        'Nom campagne': { title: {} },
        'Client': { rich_text: {} },
        'Date collecte': { date: {} },
        'Statut': {
          select: {
            options: [
              { name: 'Active', color: 'green' },
              { name: 'Terminée', color: 'gray' },
              { name: 'En optimisation', color: 'orange' },
              { name: 'En préparation', color: 'blue' },
            ],
          },
        },
        'Canal': {
          select: {
            options: [
              { name: 'Email', color: 'blue' },
              { name: 'LinkedIn', color: 'purple' },
              { name: 'Multi', color: 'pink' },
            ],
          },
        },
        'Nb prospects': { number: { format: 'number' } },
        'Secteur': { rich_text: {} },
        'Cible': { rich_text: {} },
        'Open rate global': { number: { format: 'percent' } },
        'Reply rate global': { number: { format: 'percent' } },
        'Accept rate LK': { number: { format: 'percent' } },
        'Reply rate LK': { number: { format: 'percent' } },
        'Open rate E1': { number: { format: 'percent' } },
        'Open rate E2': { number: { format: 'percent' } },
        'Open rate E3': { number: { format: 'percent' } },
        'Open rate E4': { number: { format: 'percent' } },
        'Reply rate E1': { number: { format: 'percent' } },
        'Reply rate E2': { number: { format: 'percent' } },
        'Reply rate E3': { number: { format: 'percent' } },
        'Reply rate E4': { number: { format: 'percent' } },
        'Lemlist ID': { rich_text: {} },
      },
    });
    created.resultats = resultats.id;
    console.log(`   ✅ Created (ID: ${resultats.id})`);
  }

  // ──────────────────────────────────────────
  // 2. Campagnes · Diagnostics
  // ──────────────────────────────────────────
  if (!created.diagnostics) {
    console.log('🩺 Creating "Campagnes, Diagnostics"...');
    const diagnostics = await notion.databases.create({
      parent: { type: 'page_id', page_id: parentPageId },
      title: [{ type: 'text', text: { content: 'Campagnes, Diagnostics' } }],
      icon: { type: 'emoji', emoji: '🩺' },
      properties: {
        'Campagne': { title: {} },
        'Date analyse': { date: {} },
        'Priorités': {
          multi_select: {
            options: [
              { name: 'E1', color: 'blue' },
              { name: 'E2', color: 'green' },
              { name: 'E3', color: 'orange' },
              { name: 'E4', color: 'red' },
              { name: 'L1', color: 'purple' },
              { name: 'L2', color: 'pink' },
              { name: 'Objet', color: 'yellow' },
              { name: 'Timing', color: 'gray' },
            ],
          },
        },
        'Nb messages à optimiser': { number: { format: 'number' } },
      },
    });
    created.diagnostics = diagnostics.id;
    console.log(`   ✅ Created (ID: ${diagnostics.id})`);
  }

  // ──────────────────────────────────────────
  // 3. Campagnes · Historique Versions
  // ──────────────────────────────────────────
  if (!created.historique) {
    console.log('📝 Creating "Campagnes, Historique Versions"...');
    const historique = await notion.databases.create({
      parent: { type: 'page_id', page_id: parentPageId },
      title: [{ type: 'text', text: { content: 'Campagnes, Historique Versions' } }],
      icon: { type: 'emoji', emoji: '📝' },
      properties: {
        'Campagne': { title: {} },
        'Version': { number: { format: 'number' } },
        'Date': { date: {} },
        'Messages modifiés': {
          multi_select: {
            options: [
              { name: 'E1', color: 'blue' },
              { name: 'E2', color: 'green' },
              { name: 'E3', color: 'orange' },
              { name: 'E4', color: 'red' },
              { name: 'L1', color: 'purple' },
              { name: 'L2', color: 'pink' },
            ],
          },
        },
        'Hypothèses testées': { rich_text: {} },
        'Résultat': {
          select: {
            options: [
              { name: 'En cours', color: 'yellow' },
              { name: 'Amélioré', color: 'green' },
              { name: 'Dégradé', color: 'red' },
              { name: 'Neutre', color: 'gray' },
            ],
          },
        },
      },
    });
    created.historique = historique.id;
    console.log(`   ✅ Created (ID: ${historique.id})`);
  }

  // ──────────────────────────────────────────
  // 4. Mémoire Cross-Campagne
  // ──────────────────────────────────────────
  if (!created.memoire) {
    console.log('🧠 Creating "Mémoire Cross-Campagne"...');
    const memoire = await notion.databases.create({
      parent: { type: 'page_id', page_id: parentPageId },
      title: [{ type: 'text', text: { content: 'Mémoire Cross-Campagne' } }],
      icon: { type: 'emoji', emoji: '🧠' },
      properties: {
        'Pattern': { title: {} },
        'Catégorie': {
          select: {
            options: [
              { name: 'Objets', color: 'blue' },
              { name: 'Corps', color: 'green' },
              { name: 'Timing', color: 'orange' },
              { name: 'LinkedIn', color: 'purple' },
              { name: 'Secteur', color: 'pink' },
              { name: 'Cible', color: 'yellow' },
            ],
          },
        },
        'Confiance': {
          select: {
            options: [
              { name: 'Haute', color: 'green' },
              { name: 'Moyenne', color: 'orange' },
              { name: 'Faible', color: 'red' },
            ],
          },
        },
        'Date découverte': { date: {} },
        'Secteur': {
          multi_select: {
            options: [
              { name: 'Comptabilité & Finance', color: 'blue' },
              { name: 'IT & Services', color: 'green' },
              { name: 'Immobilier', color: 'orange' },
              { name: 'RH & Recrutement', color: 'purple' },
              { name: 'Marketing & Communication', color: 'pink' },
            ],
          },
        },
        'Cible': {
          multi_select: {
            options: [
              { name: 'DAF', color: 'blue' },
              { name: 'DG', color: 'green' },
              { name: 'DRH', color: 'purple' },
              { name: 'DSI', color: 'orange' },
              { name: 'Directeur Commercial', color: 'red' },
            ],
          },
        },
      },
    });
    created.memoire = memoire.id;
    console.log(`   ✅ Created (ID: ${memoire.id})`);
  }

  // ──────────────────────────────────────────
  // Auto-save to .env
  // ──────────────────────────────────────────
  console.log('\n════════════════════════════════════════');
  console.log('✅ All 4 databases ready!');
  console.log('════════════════════════════════════════\n');

  const envEntries = {
    NOTION_PARENT_PAGE_ID: parentPageId,
    NOTION_DB_RESULTATS: created.resultats,
    NOTION_DB_DIAGNOSTICS: created.diagnostics,
    NOTION_DB_HISTORIQUE: created.historique,
    NOTION_DB_MEMOIRE: created.memoire,
  };

  appendToEnv(envEntries);

  console.log('📝 Database IDs saved to .env:');
  for (const [key, value] of Object.entries(envEntries)) {
    console.log(`   ${key}=${value}`);
  }

  console.log('\n✅ Done! Restart the server to apply: npm run dev\n');
}

main().catch((err) => {
  console.error('\n❌ Setup failed:', err.message);
  if (err.code === 'unauthorized') {
    console.error('   → Check your NOTION_TOKEN in .env');
  } else if (err.code === 'object_not_found') {
    console.error('   → Check NOTION_PARENT_PAGE_ID and share the page with your integration');
  }
  process.exit(1);
});
